config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  
  get 'dashboard', to: 'dashboard#index'
  resources :providers
  resources :banks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank.rb
class Bank < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/models/provider.rb
class Provider < ApplicationRecord
  validates :name, presence: true
  validates :nit, format: { with: /\A\d{9}-\d{1}\z/ }, allow_blank: true
  validates :contact_person_name, presence: true
  validates :contact_person_number, length: { maximum: 10 }
  validates :bank_name, inclusion: { in: Bank.pluck(:name) }
  validates :bank_account_number, length: { maximum: 15 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bank, only: %i[show edit update destroy]

  # GET /banks
  def index
    @pagy, @banks = pagy(Bank.order(created_at: :desc), items: 10)
  end

  # GET /banks/1
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  def create
    @bank = Bank.new(bank_params)

    if @bank.save
      redirect_to @bank, notice: t('bank.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /banks/1
  def update
    if @bank.update(bank_params)
      redirect_to @bank, notice: t('bank.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /banks/1
  def destroy
    @bank.destroy
    redirect_to banks_url, notice: t('bank.destroyed')
  end

  private

  def set_bank
    @bank = Bank.find(params[:id])
  end

  def bank_params
    params.require(:bank).permit(:name)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_provider, only: %i[show edit update destroy]

  # GET /providers
  def index
    @pagy, @providers = pagy(Provider.order(created_at: :desc), items: 10)
  end

  # GET /providers/1
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  def create
    @provider = Provider.new(provider_params)

    if @provider.save
      redirect_to @provider, notice: t('provider.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /providers/1
  def update
    if @provider.update(provider_params)
      redirect_to @provider, notice: t('provider.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /providers/1
  def destroy
    @provider.destroy
    redirect_to providers_url, notice: t('provider.destroyed')
  end

  private

  def set_provider
    @provider = Provider.find(params[:id])
  end

  def provider_params
    params.require(:provider).permit(:name, :nit, :contact_person_name, :contact_person_number, :bank_name, :bank_account_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def flash_class(flash_type)
    case flash_type
    when 'notice'
      'bg-green-100 text-green-700'
    when 'alert'
      'bg-red-100 text-red-700'
    else
      ''
    end
  end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
  def bank_names_for_select(form)
    form.collection_select :bank_name,
                           Bank.all,
                           :name,
                           :name,
                           {},
                           { class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' }
  end

  def attribute_or_empty_message_for(provider_attribute)
    provider_attribute.presence || t('empty_field')
  end
end

app/views/banks/_bank.html.erb
<div id="<%= dom_id bank %>">
  <tr class="hover:bg-gray-50">
    <td class="whitespace px-3 py-4 break-all">
      <%= link_to bank.name, bank, class: "text-blue-600 hover:text-blue-700 hover:underline" %>
    </td>
    <td class="whitespace-nowrap p-2 text-sm text-right">
      <%= link_to t('bank.edit'), edit_bank_path(bank), class: "rounded-lg p-2 ml-2 text-blue-500 border-blue-500 border transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none" %>
      <div class="inline-block ml-2">
        <%= button_to t('bank.destroy'), bank_path(bank), method: :delete, class: "rounded-lg p-2 ml-2 text-red-500 border-red-500 border transition duration-300 hover:bg-red-700 hover:text-white focus:outline-none", data: { turbo_confirm: t('confirm_destroy') } %>
      </div>
    </td>
  </tr>
</div>

app/views/banks/_form.html.erb
<%= form_with(model: bank, class: "contents") do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= t('errors.template.body') %></h2>
      <ul>
        <% bank.errors.each do |error| %>
          <li>- <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('bank.edit') %></h1>

  <%= render "form", bank: @bank %>

  <%= link_to t('bank.show'), @bank, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to t('back'), banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/banks/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('bank.plural') %></h1>
    <%= link_to t('bank.new'), new_bank_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

   <div id="banks" class="rounded-lg border border-gray-200 shadow-md m-5">
    <table class="w-full overflow-scroll border-collapse bg-white text-left text-sm text-gray-700">
      <thead class="bg-gray-50 text-center">
        <tr>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"><%= Bank.human_attribute_name(:name) %></th>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-100 border-t border-gray-100">
        <%= render @banks %>
      </tbody>
    </table>

    <div class="p-5">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/banks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('bank.new') %></h1>

  <%= render "form", bank: @bank %>

  <%= link_to t('back'), banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/banks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
     <div id="<%= dom_id @bank %>">
      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Bank.human_attribute_name(:name) %></strong>
        <%= @bank.name %>
      </p>
    </div>

    <%= link_to t('bank.edit'), edit_bank_path(@bank), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to t('bank.destroy'), bank_path(@bank), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium", data: { turbo_confirm: t('confirm_destroy') } %>
    </div>
    <%= link_to t('back'), banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div id="container" class="w-4/5 mx-auto">
   <h1 class="font-bold text-4xl"><%= t('dashboard.title') %></h1>
   <% presenter = DashboardPresenter.new %>
    <div class="flex flex-col sm:flex-row justify-center">
      <div class="sm:w-1/2 p-2">
        <div class="bg-white px-6 py-8 rounded-lg shadow-lg text-center">
          <h2 class="text-xl font-medium text-gray-700 mb-3"><%= t('dashboard.total_bank_count') %></h2>
          <span class="text-4xl bg-blue-100 text-blue-800 font-bold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ml-3">
            <%= presenter.banks_count %>
          </span>
        </div>
      </div>

      <div class="sm:w-1/2 p-2">
        <div class="bg-white px-6 py-8 rounded-lg shadow-lg text-center">
          <h2 class="text-xl font-medium text-gray-700 mb-3"><%= t('dashboard.total_provider_count') %></h2>
          <span class="text-4xl bg-blue-100 text-blue-800 font-bold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ml-3">
            <%= presenter.providers_count %>
          </span>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl"><%= t('home.welcome') %></h1>
  <p class="text-2xl"><%= t('home.welcome_info') %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoytrabajasRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "nav/top_nav" %>
    <div><%= render "shared/flash" %></div>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/nav/_authenticated.html.erb
<div class="flex w-full space-x-8">
  <%= link_to t('dashboard.title'), dashboard_path, class: "rounded mx-1 px-2 py-1 border border-blue-500 text-blue-700 hover:text-blue-900 hover:bg-blue-200" %>
  <%= link_to t('bank.plural'), banks_path, class: "rounded mx-1 px-2 py-1 border border-blue-500 text-blue-700 hover:text-blue-900 hover:bg-blue-200" %>
  <%= link_to t('provider.plural'), providers_path, class: "rounded mx-1 px-2 py-1 border border-blue-500 text-blue-700 hover:text-blue-900 hover:bg-blue-200" %>
</div>
<div class="px-6 py-4 flex-shrink-0">
  <%= button_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete, class: "rounded mx-1 px-2 py-1 border border-red-500 text-red-700 hover:text-red-900 hover:bg-red-200" %>
</div>

app/views/nav/_top_nav.html.erb
<nav class="bg-gray-100 shadow">
  <div class="container mx-auto flex text-gray-700 max-w-screen-2xl">
    <div class="flex flex-shrink-0 items-center px-6 py-4">
      <% if user_signed_in? %>
        <%= render "nav/authenticated" %>
      <% else %>
        <%= render "nav/unauthenticated" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/nav/_unauthenticated.html.erb
<div class="flex justify-end px-6 py-4 flex-shrink-0 space-x-8">
  <%= link_to t('home.title'), '/', class: "rounded mx-1 px-2 py-1 border border-blue-900 text-blue-900 hover:text-gray-900 hover:bg-blue-100" %>
  <%= link_to t('devise.sessions.new.sign_in'), new_user_session_path, class: "rounded mx-1 px-2 py-1 border border-blue-500 text-blue-700 hover:text-blue-900 hover:bg-blue-200" %>
  <%= link_to t('devise.registrations.new.sign_up'), new_user_registration_path, class: "rounded mx-1 px-2 py-1 border border-blue-500 text-blue-700 hover:text-blue-900 hover:bg-blue-200" %>
</div>

app/views/providers/_form.html.erb
<%= form_with(model: provider, class: "contents") do |form| %>
  <% if provider.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= t('errors.template.body') %></h2>
      <ul>
        <% provider.errors.each do |error| %>
          <li>- <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nit %>
    <%= form.text_field :nit, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_person_name %>
    <%= form.text_field :contact_person_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_person_number %>
    <%= form.text_field :contact_person_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bank_name %>
    <%= bank_names_for_select(form) %>
  </div>

  <div class="my-5">
    <%= form.label :bank_account_number %>
    <%= form.text_field :bank_account_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/providers/_provider.html.erb
<div id="<%= dom_id provider %>">
  <tr class="hover:bg-gray-50">
    <td class="whitespace px-3 py-4 text-sm break-all">
        <%= link_to provider.name, provider, class: "text-blue-600 hover:text-blue-700 hover:underline" %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm">
      <%= attribute_or_empty_message_for(provider.nit) %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm">
      <%= provider.contact_person_name %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm">
      <%= attribute_or_empty_message_for(provider.contact_person_number) %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm">
      <%= provider.bank_name %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm">
      <%= attribute_or_empty_message_for(provider.bank_account_number) %>
    </td>
    <td class="whitespace-nowrap p-2 text-sm">
      <%= link_to t('provider.edit'), edit_provider_path(provider), class: "rounded-lg p-2 ml-2 text-blue-500 border-blue-500 border transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none" %>
      <div class="inline-block ml-2">
        <%= button_to t('provider.destroy'), provider_path(provider), method: :delete, class: "rounded-lg p-2 ml-2 text-red-500 border-red-500 border transition duration-300 hover:bg-red-700 hover:text-white focus:outline-none", data: { turbo_confirm: t('confirm_destroy') } %>
      </div>
    </td>

  </tr>
</div>

app/views/providers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('provider.edit') %></h1>

  <%= render "form", provider: @provider %>

  <%= link_to t('provider.show'), @provider, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to t('back'), providers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/providers/index.html.erb
<div class="flex-row">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('provider.plural') %></h1>
    <%= link_to t('provider.new'), new_provider_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="providers" class="rounded-lg border border-gray-200 shadow-md m-5">
    <table class="w-full overflow-scroll border-collapse bg-white text-left text-sm text-gray-700">
      <thead class="bg-gray-50 text-center">
        <tr>
          <th scope="col" class="px-12 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:name) %></th>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:nit) %></th>
          <th scope="col" class="px-2 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:contact_person_name) %></th>
          <th scope="col" class="px-2 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:contact_person_number) %></th>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:bank_name) %></th>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"><%= Provider.human_attribute_name(:bank_account_number) %></th>
          <th scope="col" class="px-6 py-4 font-medium text-gray-900"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-100 border-t border-gray-100">
        <%= render @providers %>
      </tbody>
    </table>

    <div class="p-5">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/providers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('provider.new') %></h1>

  <%= render "form", provider: @provider %>

  <%= link_to t('back'), providers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/providers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <div id="<%= dom_id @provider %>">
      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:name) %></strong>
        <%= @provider.name %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:nit) %></strong>
        <%= attribute_or_empty_message_for(@provider.nit) %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:contact_person_name) %></strong>
        <%= @provider.contact_person_name %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:contact_person_number) %></strong>
        <%= attribute_or_empty_message_for(@provider.contact_person_number) %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:bank_name) %></strong>
        <%= @provider.bank_name %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1"><%= Provider.human_attribute_name(:bank_account_number) %></strong>
        <%= attribute_or_empty_message_for(@provider.bank_account_number) %>
      </p>
    </div>

    <%= link_to t('provider.edit'), edit_provider_path(@provider), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to t('provider.destroy'), provider_path(@provider), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium", data: { turbo_confirm: t('confirm_destroy') } %>
    </div>
    <%= link_to t('back'), providers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flex rounded-lg p-4 mb-4 text-sm <%= flash_class(flash_type) %>" role="alert">
    <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <div><span class="font-medium"><%= message %></span></div>
  </div>
<% end %>